site_name: Budget Docs
site_url: https://griadooss.github.io/budget-docs/
repo_url: https://github.com/griadooss/budget-docs
nav:
  - Home: introduction.md
  - Quickstart: quickstart.md
  - Guides:
      - User Manual:
          - Basic Overview: guides/user-manual/basic-overview.md
          - Menu Reference: guides/user-manual/menu-reference.md
          - Basic Operations: guides/user-manual/basic-operations.md
          - Getting Started: guides/user-manual/getting-started.md
      - Daily Tasks:
          - Categorizing: guides/daily-tasks/categorizing.md
          - Reconciling: guides/daily-tasks/reconciling.md
          - Importing: guides/daily-tasks/importing.md
      - Monthly Tasks:
          - End of Month: guides/monthly-tasks/end-of-month.md
          - Reporting: guides/monthly-tasks/reporting.md
      - Yearly Tasks:
          - End of Year:
              - Overview: guides/yearly-tasks/end-of-year/overview.md
              - Setup: guides/yearly-tasks/end-of-year/setup.md
              - Developer Guide: guides/yearly-tasks/end-of-year/developer-guide.md
      - System:
          - Version: guides/system/version.md
          - Changelog: guides/system/changelog.md
      - Troubleshooting:
          - Common Issues: guides/troubleshooting/common-issues.md
          - Using AI Help: guides/troubleshooting/using-ai-help.md
