[build]
  command = "npm install && mintlify dev"
  publish = "."

[build.environment]
  NODE_VERSION = "18"

[[plugins]]
  package = "netlify-plugin-minify-html"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200